import './/styles/globals.css'; 
import { Poppins } from 'next/font/google'; 
export const metadata = {
  title: 'Meme Website',
  description: 'Generated by Next.js',
}
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="lemonade">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
